OBJS = $(CSRCS:.c=.o)
OBJS += $(ASMSRCS:.s=.o)
DST_OBJS = $(addprefix $(OBJ_DIR)/, $(OBJS))

DST_TARGET = $(OBJ_DIR)/$(TARGET).elf
DST_TARGET += $(OBJ_DIR)/$(TARGET).bin

.PRECIOUS: $(OBJ_DIR)/%.o

all:: $(DST_OBJS) $(DST_TARGET)

$(OBJ_DIR)/%.bin: $(OBJ_DIR)/$(TARGET).elf
	$(OBJCOPY) -O binary $< $@

$(OBJ_DIR)/%.elf: $(DST_OBJS)
	$(LD) $^ $(LDFLAGS) -o $@

$(OBJ_DIR)/%.o: %.c
	mkdir -p "$(OBJ_DIR)/`dirname $<`"
	$(CC) $(CFLAGS) -o $@ -c $<  -D__TLOG_FILE__=\"$(shell basename $< .c)\"

$(OBJ_DIR)/%.o: %.s
	mkdir -p "$(OBJ_DIR)/`dirname $<`"
	$(AS) $(ASMFLAGS) -o $@ -c $<

clean:
	rm $(DST_OBJS) $(DST_TARGET) -f

flash: $(OBJ_DIR)/$(TARGET).bin
	st-flash --reset write $(OBJ_DIR)/$(TARGET).bin 0x08000000
