#pragma once

#include "mem.h"
#include "stm32.h"

/*----------------------------------------------------------------------------*/
#define TIM_CR1(base)                                            R32(base, 0x00)
#define CR1_CEN                                                      UINT8_C( 0)
#define CR1_UDIS                                                     UINT8_C( 1)
#define CR1_URS                                                      UINT8_C( 2)
#define CR1_OPM                                                      UINT8_C( 3)
#define CR1_DIR                                                      UINT8_C( 4)
#define CR1_CMS                                                      UINT8_C( 5)
#define CR1_ARPE                                                     UINT8_C( 7)
#define CR1_CKD                                                      UINT8_C( 8)
/*----------------------------------------------------------------------------*/
#define TIM_CR2(base)                                            R32(base, 0x04)
#define CR2_CCPC                                                     UINT8_C( 0)
#define CR2_CCUS                                                     UINT8_C( 2)
#define CR2_CCDS                                                     UINT8_C( 3)
#define CR2_MMS                                                      UINT8_C( 4)
#define CR2_TI1S                                                     UINT8_C( 7)
#define CR2_OIS1                                                     UINT8_C( 8)
#define CR2_OIS1N                                                    UINT8_C( 9)
#define CR2_OIS2                                                     UINT8_C(10)
#define CR2_OIS2N                                                    UINT8_C(11)
#define CR2_OIS3                                                     UINT8_C(12)
#define CR2_OIS3N                                                    UINT8_C(13)
#define CR2_OIS4                                                     UINT8_C(14)
/*----------------------------------------------------------------------------*/
#define TIM_SMCR(base)                                           R32(base, 0x08)
#define SMCR_SMS                                                     UINT8_C( 0)
#define SMCR_TS                                                      UINT8_C( 4)
#define SMCR_MSM                                                     UINT8_C( 7)
#define SMCR_ETF                                                     UINT8_C( 8)
#define SMCR_ETPS                                                    UINT8_C(12)
#define SMCR_ECE                                                     UINT8_C(14)
#define SMCR_ETP                                                     UINT8_C(15)
/*----------------------------------------------------------------------------*/
#define TIM_DIER(base)                                           R32(base, 0x0C)
#define DIER_UIE                                                     UINT8_C( 0)
#define DIER_CC1IE                                                   UINT8_C( 1)
#define DIER_CC2IE                                                   UINT8_C( 2)
#define DIER_CC3IE                                                   UINT8_C( 3)
#define DIER_CC4IE                                                   UINT8_C( 4)
#define DIER_COMIE                                                   UINT8_C( 5)
#define DIER_TIE                                                     UINT8_C( 6)
#define DIER_BIE                                                     UINT8_C( 7)
#define DIER_UDE                                                     UINT8_C( 8)
#define DIER_CC1DE                                                   UINT8_C( 9)
#define DIER_CC2DE                                                   UINT8_C(10)
#define DIER_CC3DE                                                   UINT8_C(11)
#define DIER_CC4DE                                                   UINT8_C(12)
#define DIER_COMDE                                                   UINT8_C(13)
#define DIER_TDE                                                     UINT8_C(14)
/*----------------------------------------------------------------------------*/
#define TIM_SR(base)                                             R32(base, 0x10)
#define SR_UIF                                                       UINT8_C( 0)
#define SR_CC1IF                                                     UINT8_C( 1)
#define SR_CC2IF                                                     UINT8_C( 2)
#define SR_CC3IF                                                     UINT8_C( 3)
#define SR_CC4IF                                                     UINT8_C( 4)
#define SR_COMIF                                                     UINT8_C( 5)
#define SR_TIF                                                       UINT8_C( 6)
#define SR_BIF                                                       UINT8_C( 7)
#define SR_CC1OF                                                     UINT8_C( 9)
#define SR_CC2OF                                                     UINT8_C(10)
#define SR_CC3OF                                                     UINT8_C(11)
#define SR_CC4OF                                                     UINT8_C(12)
/*----------------------------------------------------------------------------*/
#define TIM_EGR(base)                                            R32(base, 0x14)
#define EGR_UG                                                       UINT8_C( 0)
#define EGR_CC1G                                                     UINT8_C( 1)
#define EGR_CC2G                                                     UINT8_C( 2)
#define EGR_CC3G                                                     UINT8_C( 3)
#define EGR_CC4G                                                     UINT8_C( 4)
#define EGR_COMG                                                     UINT8_C( 5)
#define EGR_TG                                                       UINT8_C( 6)
#define EGR_BG                                                       UINT8_C( 7)
/*----------------------------------------------------------------------------*/
#define TIM_CCMR1(base)                                          R32(base, 0x18)
#define CCMR1_CC1S                                                   UINT8_C( 0)
#define CCMR1_OC1FE                                                  UINT8_C( 2)
#define CCMR1_OC1PE                                                  UINT8_C( 3)
#define CCMR1_OC1M                                                   UINT8_C( 4)
#define CCMR1_OC1CE                                                  UINT8_C( 7)
#define CCMR1_CC2S                                                   UINT8_C( 8)
#define CCMR1_OC2FE                                                  UINT8_C(10)
#define CCMR1_OC2PE                                                  UINT8_C(11)
#define CCMR1_OC2M                                                   UINT8_C(12)
#define CCMR1_OC2CE                                                  UINT8_C(15)
#define CCMR1_IC1PSC                                                 UINT8_C( 2)
#define CCMR1_IC1F                                                   UINT8_C( 4)
#define CCMR1_IC2PSC                                                 UINT8_C(10)
#define CCMR1_IC2F                                                   UINT8_C(12)
/*----------------------------------------------------------------------------*/
#define TIM_CCMR2(base)                                          R32(base, 0x1C)
#define CCMR2_CC3S                                                   UINT8_C( 0)
#define CCMR2_OC3FE                                                  UINT8_C( 2)
#define CCMR2_OC3PE                                                  UINT8_C( 3)
#define CCMR2_OC3M                                                   UINT8_C( 4)
#define CCMR2_OC3CE                                                  UINT8_C( 7)
#define CCMR2_CC4S                                                   UINT8_C( 8)
#define CCMR2_OC4FE                                                  UINT8_C(10)
#define CCMR2_OC4PE                                                  UINT8_C(11)
#define CCMR2_OC4M                                                   UINT8_C(12)
#define CCMR2_OC4CE                                                  UINT8_C(15)
#define CCMR2_IC3PSC                                                 UINT8_C( 2)
#define CCMR2_IC3F                                                   UINT8_C( 4)
#define CCMR2_IC4PSC                                                 UINT8_C(10)
#define CCMR2_IC4F                                                   UINT8_C(12)
/*----------------------------------------------------------------------------*/
#define TIM_CCER(base)                                           R32(base, 0x20)
#define CCER_CC1E                                                    UINT8_C( 0)
#define CCER_CC1P                                                    UINT8_C( 1)
#define CCER_CC1NE                                                   UINT8_C( 2)
#define CCER_CC1NP                                                   UINT8_C( 3)
#define CCER_CC2E                                                    UINT8_C( 4)
#define CCER_CC2P                                                    UINT8_C( 5)
#define CCER_CC2NE                                                   UINT8_C( 6)
#define CCER_CC2NP                                                   UINT8_C( 7)
#define CCER_CC3E                                                    UINT8_C( 8)
#define CCER_CC3P                                                    UINT8_C( 9)
#define CCER_CC3NE                                                   UINT8_C(10)
#define CCER_CC3NP                                                   UINT8_C(11)
#define CCER_CC4E                                                    UINT8_C(12)
#define CCER_CC4P                                                    UINT8_C(13)
/*----------------------------------------------------------------------------*/
#define TIM_CNT(base)                                            R32(base, 0x24)
/*----------------------------------------------------------------------------*/
#define TIM_PSC(base)                                            R32(base, 0x28)
/*----------------------------------------------------------------------------*/
#define TIM_ARR(base)                                            R32(base, 0x2C)
/*----------------------------------------------------------------------------*/
#define TIM_RCR(base)                                            R32(base, 0x30)
/*----------------------------------------------------------------------------*/
#define TIM_CCR1(base)                                           R32(base, 0x34)
/*----------------------------------------------------------------------------*/
#define TIM_CCR2(base)                                           R32(base, 0x38)
/*----------------------------------------------------------------------------*/
#define TIM_CCR3(base)                                           R32(base, 0x3C)
/*----------------------------------------------------------------------------*/
#define TIM_CCR4(base)                                           R32(base, 0x40)
/*----------------------------------------------------------------------------*/
#define TIM_BDTR(base)                                           R32(base, 0x44)
#define BDTR_DTG                                                     UINT8_C( 0)
#define BDTR_LOCK                                                    UINT8_C( 8)
#define BDTR_OSSI                                                    UINT8_C(10)
#define BDTR_OSSR                                                    UINT8_C(11)
#define BDTR_BKE                                                     UINT8_C(12)
#define BDTR_BKP                                                     UINT8_C(13)
#define BDTR_AOE                                                     UINT8_C(14)
#define BDTR_MOE                                                     UINT8_C(15)
/*----------------------------------------------------------------------------*/
#define TIM_DCR(base)                                            R32(base, 0x48)
#define DCR_DBA                                                      UINT8_C( 0)
#define DCR_DBL                                                      UINT8_C( 8)
/*----------------------------------------------------------------------------*/
#define TIM_DMAR(base)                                           R32(base, 0x4C)
/*----------------------------------------------------------------------------*/
#define TIM_ENABLE(base)                           TIM_CR1(base) |= M1(CR1_CEN)
#define TIM_DISABLE(base)                          TIM_CR1(base) &= ~M1(CR1_CEN)
#define TIM_AUTO_RELOAD_PRELOAD_ENABLE(base)       TIM_CR1(base) |= M1(CR1_ARPE)
#define TIM_COUNT_UP(base)                         TIM_CR1(base) &= ~M1(CR1_DIR)
#define TIM_COUNT_DOWN(base)                       TIM_CR1(base) |= M1(CR1_DIR)

#define TIM_UPDATE_INT_ENABLE(base)              TIM_DIER(base) |= M1(DIER_UIE)
#define TIM_UPDATE_INT_DISABLE(base)             TIM_DIER(base) &= ~M1(DIER_UIE)

#define TIM_UPDATE_INT_CLEAR(base)                   TIM_SR(base) &= ~M1(SR_UIF)

#define TIM_RD_CNTR(base)                                TIM_CNT(base)
#define TIM_WR_CNTR(base, value)                         TIM_CNT(base) = (value)

// freq_psc = freq_src / (value + 1)
#define TIM_CLK_DIV(base, value)                         TIM_PSC(base) = (value)

#define TIM_RD_TARGET(base)                              TIM_ARR(base)
#define TIM_WR_TARGET(base, value)                       TIM_ARR(base) = (value)
